RELATIONSHIP = (
    ("father", "father"),
    ("mother", "mother"),
    ("son", "son"),
    ("daughter", "daughter"),
    ("husband", "husband"),
    ("wife", "wife"),
    ("brother", "brother"),
    ("sister", "sister"),
    ("grandfather", "grandfather"),
    ("grandmother", "grandmother"),
    ("grandson", "grandson"),
    ("granddaughter", "granddaughter"),
    ("uncle", "uncle"),
    ("aunt", "aunt"),
    ("nephew", "nephew"),
    ("niece", "niece"),
    ("cousin", "cousin"),
    ("friend", "friend"),
    ("friend with family", "friend with family"),
)
