# Generated by Django 2.2 on 2021-02-10 10:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='You profile image', null=True, upload_to='', verbose_name=accounts.models.upload_dir),
        ),
    ]
