# Generated by Django 2.2 on 2022-08-23 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mp3.validators
import nwaben.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('album_name', models.CharField(max_length=255)),
                ('album_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('genre', models.CharField(max_length=100)),
                ('album_logo', models.ImageField(blank=True, null=True, upload_to='album/covers')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.ManyToManyField(blank=True, related_name='owned_by', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Albums',
                'ordering': ('-date_uploaded',),
                'unique_together': {('album_name',)},
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=225)),
                ('slug', models.SlugField()),
                ('audio_file', models.FileField(blank=True, max_length=200, null=True, storage=nwaben.storage_backends.PublicMediaStorage(), upload_to='album/songs', validators=[mp3.validators.validate_file_extension])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp3.Album')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
