# Generated by Django 2.2 on 2020-08-10 18:58

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mp3.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('album_name', models.CharField(max_length=255)),
                ('album_token', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField()),
                ('genre', models.CharField(max_length=100)),
                ('album_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=mp3.models.upload_dir)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Albums',
                'ordering': ('date_uploaded',),
                'unique_together': {('artist', 'album_name')},
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_token', models.CharField(max_length=225)),
                ('song_title', models.CharField(max_length=225)),
                ('slug', models.SlugField()),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('song_url', models.URLField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp3.Album')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
