# Generated by Django 3.0.7 on 2020-06-17 14:44

import archive.models
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('album_name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('genre', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('album_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name=archive.models.upload_dir)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Archives',
                'ordering': ('date_uploaded',),
                'unique_together': {('artist', 'album_name')},
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('audio_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name=archive.models.upload_dir)),
                ('track_number', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Album')),
            ],
        ),
    ]
